# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - end_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - revolute_1
      - revolute_8
      - revolute_9
    action_ns: follow_joint_trajectory
    default: true
  end_controller:
    type: FollowJointTrajectory
    joints:
      - revolute_11
      - gripper_open_joint
      - gripper_right_joint
    action_ns: follow_joint_trajectory
    default: true